language: python
python:
  - "3.9"

# services:
#   - docker

addons:
  sonarcloud:
    organization: "thecodingkittens"

# before_install:
#   - docker build -t image .
#   - docker run -d -p 8000:8000 --name travis image

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  # - docker exec -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -i travis pytest --cov=app
  - pytest --cov=app
  - sonar-scanner

after_success:
  - coveralls
