language: python
python:
  - "3.9"

services:
  - docker

addons:
  sonarcloud:
    organization: "thecodingkittens" # the key of the org you chose at step #3

before_install:
  - docker build -t image .
  - docker run -d -p 8000:8000 --name travis image

script:
  - docker exec -i travis pytest
  - sonar-scanner
