version: "3.8"

services:

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MONGO
      - MONGO_INITDB_ROOT_PASSWORD=SECRET

  api:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_STORE_DB_INDEX=0
    env_file:
      - .env
    volumes:
      - ./data:/data
    depends_on:
      - redis
    ports:
      - "8000:8000"
